export const ActionTypes = {
  CREATE_MEDICINE_SUCCESS: 'CREATE_MEDICINE_SUCCESS',
  CREATE_MEDICINE_ERROR: 'CREATE_MEDICINE_ERROR',

  UPDATE_MEDICINE_SUCCESS: 'UPDATE_MEDICINE_SUCCESS',
  UPDATE_MEDICINE_ERROR: 'UPDATE_MEDICINE_ERROR',

  DELETE_MEDICINE_SUCCESS: 'DELETE_MEDICINE_SUCCESS',
  DELETE_MEDICINE_ERROR: 'DELETE_MEDICINE_ERROR',
};
